package com.ewaves.util;

import org.springframework.stereotype.Component;

@Component
public class MailUI {

	public StringBuilder forgotPasswordTemplet(String url, String userName) {

		StringBuilder sb = new StringBuilder("");

		sb.append("<div bgcolor=\"#F2F2F2\">" + "	<center>"
				+ "	<table align=\"center\" bgcolor=\"#F2F2F2\" border=\"0\" cellpadding=\"0\""
				+ "cellspacing=\"0\" height=\"100%\" width=\"100%\"" + "id=\"m_8956386059296342471bodyTable\">"
				+ "<tbody>" + "	<tr>" + "		<td align=\"center\" style=\"padding: 10px\" valign=\"top\""
				+ "id=\"m_8956386059296342471bodyCell\"><span"
				+ "style=\"color: #f2f2f2; display: none; font-size: 0px; height: 0px; width: 0px\">You"
				+ "	requested a password reset for your account.</span>"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\""
				+ "	style=\"max-width: 640px\" width=\"100%\"" + "	class=\"m_8956386059296342471emailContainer\">"
				+ "	<tbody>" + "					<tr>" + "<td align=\"center\" valign=\"top\">"
				+ "	<table align=\"center\" bgcolor=\"#FFFFFF\" border=\"0\"" + "	cellpadding=\"0\" cellspacing=\"0\""
				+ "	style=\"background-color: #ffffff; border-bottom: 2px solid #e5e5e5; border-radius: 4px\""
				+ "	width=\"100%\">" + "	<tbody>" + "		<tr>" + "	<td align=\"center\""
				+ "		style=\"padding-right: 20px; padding-left: 20px\"" + "	valign=\"top\">"
				+ "	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"" + "		width=\"100%\">"
				+ "		<tbody>" + "			<tr>" + "				<td align=\"left\" valign=\"top\""
				+ "					style=\"padding-top: 40px; padding-bottom: 30px\">"
				+ "					<a href=\"http://www.mailchimp.com/\" title=\"MailChimp\""
				+ "					style=\"text-decoration: none\" target=\"_blank\"><img"
				+ "						src=\"https://ci4.googleusercontent.com/proxy/KJxJTdDPY2DLQiqdj4g_J3VkqTYjt_EXYx0BARJ0ePga7-_u_uUPoP2cTpU4VhZzr8I9k7KJtn1pav4au1ZfT0H57LWTp7KHVNaQGc8Sf8IyW_kxfq8M-JkV0SSgQ5vh6xgDYKLthHGiXs-dz3Q2lk9g1ohPDsBDWbpfm_c=s0-d-e1-ft#https://gallery.mailchimp.com/74afb1b557e9265273c38e56b/images/4a62edaa-918c-41b1-9771-3848726ee255.png\" width=\"164\" style=\"max-width:328px;padding-bottom:0;display:inline!important;vertical-align:bottom\""
				+ "						alt=\"MailChimp\" width=\"150\""
				+ "						class=\"m_8956386059296342471logoImage CToWUd\""
				+ "						style=\"border: 0; color: #000000; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 24px; font-weight: bold; height: auto; letter-spacing: -2px; line-height: 115%; text-align: center; line-height: 100%; outline: none; text-decoration: none\"></a>"
				+ "				</td>" + "			</tr>" + "			<tr>"
				+ "				<td style=\"padding-bottom: 20px\" valign=\"top\">" + "					<h1"
				+ "						style=\"color: #606060; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 28px; font-style: normal; font-weight: 600; line-height: 36px; letter-spacing: normal; margin: 0; padding: 0; text-align: left\">Forgot"
				+ "						your password? Let's get you a new one.</h1>" + "				</td>"
				+ "			</tr>" + "			<tr>"
				+ "				<td style=\"padding-bottom: 20px\" valign=\"top\">" + "					<p"
				+ "						style=\"color: #606060; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 0; margin-top: 0; text-align: left\">"
				+ "						We got a request to change the password for the"
				+ "						account with the username <strong>" + userName + "</strong>."
				+ "					</p>" + "					<p"
				+ "						style=\"color: #606060; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 0; margin-top: 0; text-align: left\">If"
				+ "						you don't want to reset your password, you can ignore"
				+ "						this email.</p>" + "					" + "				</td>"
				+ "			</tr>" + "			<tr>"
				+ "				<td align=\"center\" style=\"padding-bottom: 60px\""
				+ "					valign=\"top\">"
				+ "					<table align=\"center\" border=\"0\" cellpadding=\"0\""
				+ "						cellspacing=\"0\" width=\"100%\">" + "						<tbody>"
				+ "							<tr>"
				+ "								<td align=\"center\" valign=\"middle\"><a href=" + url + ""
				+ "									style=\"background-color: #6dc6dd; border-collapse: separate; border-top: 20px solid #6dc6dd; border-right: 20px solid #6dc6dd; border-bottom: 20px solid #6dc6dd; border-left: 20px solid #6dc6dd; border-radius: 3px; color: #ffffff; display: inline-block; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 600; letter-spacing: .3px; text-decoration: none\""
				+ "									target=\"_blank\"" + "									>Reset"
				+ "										Your Password</a></td>" + "							</tr>"
				+ "						</tbody>" + "					</table>" + "				</td>"
				+ "			</tr>" + "		</tbody>" + "		</table>" + "	</td>" + "		</tr>"
				+ "		</tbody>" + "	</table>" + "						</td>" + "		</tr>"
				+ "					<tr>" + "			<td align=\"center\" valign=\"top\">"
				+ "				<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">"
				+ "					<tbody>" + "						<tr>"
				+ "							<td align=\"center\" valign=\"top\""
				+ "								class=\"m_8956386059296342471footerContent\""
				+ "								style=\"color: #606060; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px; font-weight: 400; line-height: 24px; padding-top: 40px; padding-bottom: 40px; text-align: center\">"
				+ "								<p"
				+ "									style=\"color: #606060; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px; font-weight: 400; line-height: 24px; padding-top: 0; margin: 0; text-align: center\">"
				+ "									© 2001-2017 MailChimp<sup>®</sup>, All Rights Reserved.<br>675"
				+ "									Ponce De Leon Ave NE • Suite 5000 • Atlanta, GA 30308 USA"
				+ "								</p> <a href=\"http://www.mailchimp.com/contact/\""
				+ "								style=\"color: #6dc6dd; text-decoration: none\""
				+ "								class=\"m_8956386059296342471utilityLink\" target=\"_blank\""
				+ "								data-saferedirecturl=\"https://www.google.com/url?hl=en&amp;q=http://www.mailchimp.com/contact/&amp;source=gmail&amp;ust=1489485235797000&amp;usg=AFQjCNGr178s90YdOQchGpJSlnqFEL0RbQ\">Contact"
				+ "									Us</a>" + "							</td>"
				+ "						</tr>" + "					</tbody>" + "				</table>"
				+ "						</td>" + "		</tr>" + "				</tbody>" + "</table></td>" + "	</tr>"
				+ "</tbody>" + "		</table>" + "	</center>" + "	<div class=\"yj6qo\"></div>"
				+ "	<div class=\"adL\"></div>" + "</div>");

		return sb;
	}

	public StringBuilder sendMailTemplet(String url, String userName,String firstName) {

		StringBuilder sb = new StringBuilder("");

		sb.append("<div bgcolor=\"#F2F2F2\">" + "	<center>"
				+ "	<table align=\"center\" bgcolor=\"#F2F2F2\" border=\"0\" cellpadding=\"0\""
				+ "cellspacing=\"0\" height=\"100%\" width=\"100%\"" + "id=\"m_8956386059296342471bodyTable\">"
				+ "<tbody>" + "	<tr>" + "		<td align=\"center\" style=\"padding: 10px\" valign=\"top\""
				+ "id=\"m_8956386059296342471bodyCell\"><span"
				+ "style=\"color: #f2f2f2; display: none; font-size: 0px; height: 0px; width: 0px\">You"
				+ "	requested a password reset for your account.</span>"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\""
				+ "	style=\"max-width: 640px\" width=\"100%\"" + "	class=\"m_8956386059296342471emailContainer\">"
				+ "	<tbody>" + "					<tr>" + "<td align=\"center\" valign=\"top\">"
				+ "	<table align=\"center\" bgcolor=\"#FFFFFF\" border=\"0\"" + "	cellpadding=\"0\" cellspacing=\"0\""
				+ "	style=\"background-color: #ffffff; border-bottom: 2px solid #e5e5e5; border-radius: 4px\""
				+ "	width=\"100%\">" + "	<tbody>" + "		<tr>" + "	<td align=\"center\""
				+ "		style=\"padding-right: 20px; padding-left: 20px\"" + "	valign=\"top\">"
				+ "	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"" + "		width=\"100%\">"
				+ "		<tbody>" + "			<tr>" + "				<td align=\"left\" valign=\"top\""
				+ "					style=\"padding-top: 40px; padding-bottom: 30px\">"
				+ "					<a href=\"http://www.mailchimp.com/\" title=\"MailChimp\""
				+ "					style=\"text-decoration: none\" target=\"_blank\"><img"
				+ "						src=\"https://ci4.googleusercontent.com/proxy/KJxJTdDPY2DLQiqdj4g_J3VkqTYjt_EXYx0BARJ0ePga7-_u_uUPoP2cTpU4VhZzr8I9k7KJtn1pav4au1ZfT0H57LWTp7KHVNaQGc8Sf8IyW_kxfq8M-JkV0SSgQ5vh6xgDYKLthHGiXs-dz3Q2lk9g1ohPDsBDWbpfm_c=s0-d-e1-ft#https://gallery.mailchimp.com/74afb1b557e9265273c38e56b/images/4a62edaa-918c-41b1-9771-3848726ee255.png\" width=\"164\" style=\"max-width:328px;padding-bottom:0;display:inline!important;vertical-align:bottom\""
				+ "						alt=\"MailChimp\" width=\"150\""
				+ "						class=\"m_8956386059296342471logoImage CToWUd\""
				+ "						style=\"border: 0; color: #000000; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 24px; font-weight: bold; height: auto; letter-spacing: -2px; line-height: 115%; text-align: center; line-height: 100%; outline: none; text-decoration: none\"></a>"
				+ "				</td>" + "			</tr>" + "			<tr>"
				+ "				<td style=\"padding-bottom: 20px\" valign=\"top\">" + "					<h1"
				+ "						style=\"color: #606060; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 28px; font-style: normal; font-weight: 600; line-height: 36px; letter-spacing: normal; margin: 0; padding: 0; text-align: left\">Congratulation!!!"
				+ "						</h1>" + "				</td>" + "			</tr>" + "			<tr>"
				+ "				<td style=\"padding-bottom: 20px\" valign=\"top\">" + "					<p"
				+ "						style=\"color: #606060; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 0; margin-top: 0; text-align: left\">"
				+ "						 Welcome "+firstName +",and thank tou registering at DreamHostel."
				+ "						your account has now been created and you can log in by using Username and Password "
				+ " by visiting our website or at the following url:: <strong>" + userName + "</strong>."
				+ "					</p>" + "					<p"
				+ "						style=\"color: #606060; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 400; line-height: 24px; padding-top: 0; margin-top: 0; text-align: left\">If"
				+ "						Upon logging in,you will ale to access other service and lot more."
				+ "						your Acount Information:.</p><p>your Acount Information:</p><p>Email:</p>"
				+ "					" + "				</td>" + "			</tr>" + "			<tr>"
				+ "				<td align=\"center\" style=\"padding-bottom: 60px\""
				+ "					valign=\"top\">"
				+ "					<table align=\"center\" border=\"0\" cellpadding=\"0\""
				+ "						cellspacing=\"0\" width=\"100%\">" + "						<tbody>"
				+ "							<tr>"
				+ "								<td align=\"center\" valign=\"middle\"><a href=" + url + ""
				+ "									style=\"background-color: #6dc6dd; border-collapse: separate; border-top: 20px solid #6dc6dd; border-right: 20px solid #6dc6dd; border-bottom: 20px solid #6dc6dd; border-left: 20px solid #6dc6dd; border-radius: 3px; color: #ffffff; display: inline-block; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 600; letter-spacing: .3px; text-decoration: none\""
				+ "									target=\"_blank\""
				+ "									>Login Here!!!" + "										</a></td>"
				+ "							</tr>" + "						</tbody>" + "					</table>"
				+ "				</td>" + "			</tr>" + "		</tbody>" + "		</table>" + "	</td>"
				+ "		</tr>" + "		</tbody>" + "	</table>" + "						</td>" + "		</tr>"
				+ "					<tr>" + "			<td align=\"center\" valign=\"top\">"
				+ "				<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">"
				+ "					<tbody>" + "						<tr>"
				+ "							<td align=\"center\" valign=\"top\""
				+ "								class=\"m_8956386059296342471footerContent\""
				+ "								style=\"color: #606060; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px; font-weight: 400; line-height: 24px; padding-top: 40px; padding-bottom: 40px; text-align: center\">"
				+ "								<p"
				+ "									style=\"color: #606060; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px; font-weight: 400; line-height: 24px; padding-top: 0; margin: 0; text-align: center\">"
				+ "									© 2001-2017 MailChimp<sup>®</sup>, All Rights Reserved.<br>675"
				+ "									Ponce De Leon Ave NE • Suite 5000 • Atlanta, GA 30308 USA"
				+ "								</p> <a href=\"http://www.mailchimp.com/contact/\""
				+ "								style=\"color: #6dc6dd; text-decoration: none\""
				+ "								class=\"m_8956386059296342471utilityLink\" target=\"_blank\""
				+ "								data-saferedirecturl=\"https://www.google.com/url?hl=en&amp;q=http://www.mailchimp.com/contact/&amp;source=gmail&amp;ust=1489485235797000&amp;usg=AFQjCNGr178s90YdOQchGpJSlnqFEL0RbQ\">Contact"
				+ "									Us</a>" + "							</td>"
				+ "						</tr>" + "					</tbody>" + "				</table>"
				+ "						</td>" + "		</tr>" + "				</tbody>" + "</table></td>" + "	</tr>"
				+ "</tbody>" + "		</table>" + "	</center>" + "	<div class=\"yj6qo\"></div>"
				+ "	<div class=\"adL\"></div>" + "</div>");

		return sb;
	}

}
